# Generated by Django 4.2.1 on 2023-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualificationsName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScientistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=500)),
                ('NqfLevel', models.IntegerField()),
                ('QualificationName', models.CharField(max_length=500)),
                ('Industry', models.CharField(max_length=500)),
                ('WorkedExperience', models.IntegerField()),
                ('EvalResults', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.CharField(max_length=500)),
            ],
        ),
    ]
